name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  CONTAINER_REGISTRY: ghcr.io
  IMAGE_NAME: mario-s-hunt

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker container
        run: |
          IMAGE_TAG=${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}:latest
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy on Remote Machine
        run: |
          echo "AUTH0_CLIENT_ID=NoE5nMqJfxkgb7GmEErmW0S4ycLbYPAf">> .env
          echo "AUTH0_CLIENT_SECRET=SFj80H0lLFVfj1KXjAsI5uPvGELs2TrdKelDSGbwGQwM1eIGzs_huyJbaU2OsA-u">> .env
          echo "AUTH0_DOMAIN=dev-joidvb5fao8vtzv4.us.auth0.com">> .env
          echo "APP_SECRET_KEY=05a9d14e4902bd510b554f09d12a327da5b8cc3c0ab40f94856acb567845f48f">> .env
          echo "USERNAME=bowser@mariohub.com">> .env
          echo "ADMIN=admin@mariohub.com">> .env
          echo "ADMIN_PASSWORD=H3Y@dm!nH3Re#" >> .env
          echo "MYSQL_ROOT_PASSWORD=root@123" >> .env
          echo "MYSQL_DB=mariohunt" >> .env
          echo "MYSQL_USER=root" >> .env
          echo "GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}" >> .env
          scp .env ubuntu@13.201.64.197:/home/ubuntu/.env
          scp .github/workflows/deploy.sh ubuntu@13.201.64.197:/home/ubuntu/deploy.sh
          scp docker-compose.yml ubuntu@13.201.64.197:/home/ubuntu/docker-compose.yml
          ssh ubuntu@13.201.64.197 "chmod +x deploy.sh"
          ssh ubuntu@13.201.64.197 "./deploy.sh"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
